name: AiMemo
options:
  bundleIdPrefix: art.lazying
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    SWIFT_VERSION: "5.9"
    PRODUCT_BUNDLE_IDENTIFIER: art.lazying.memo
    INFOPLIST_FILE: AiMemo/Resources/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  AiMemo:
    type: application
    platform: iOS
    sources:
      - AiMemo
